export enum PageName {
  INDEX = 'index',
  FABRICATORS = 'fabricators',
  CATEGORIES = 'categories',
  CATEGORY = 'categories/:categoryLink',
  FABRICATOR = 'fabricators/:fabricatorLink',
  FABRICATOR_CATEGORY = 'fabricators/:fabricatorLink/*',
  DELIVERY = 'delivery',
  GUARANTEES = 'guarantees',
  FOR_SUPPLIERS = 'for-suppliers',
  ABOUT = 'about',
  CONTACTS = 'contacts',
  AUTH = 'auth',
  ADMIN = 'admin',
  ADMIN_EDIT = 'admin/edit',
  ADMIN_CREATE = 'admin/create',
  PRODUCT = 'products/:productLink',
  SEARCH = 'search',
}
